[package]
name = "sce_app_editor-patch"
version = "0.0.0-dev"
edition = "2021"
description = "编辑器补丁：给星火编辑器打补丁，解除使用限制并支持可勾选的补丁模块"
license = "AGPL-3.0"
repository = "https://github.com/woaye168/sce_app_editor-patch"

[[bin]]
name = "sce_app_editor-patch"
path = "src/main.rs"

[dependencies]
eframe = "0.29"
egui = "0.29"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rfd = "0.15"
include_dir = "0.7"
sha2 = "0.10"
encoding_rs = "0.8"
anyhow = "1"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls", "json"] }
image = { version = "0.25", default-features = false, features = ["png"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_System_Console", "Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_Graphics_Gdi", "Win32_System_Threading", "Win32_Security"] }
windows-capture = "1"

[dev-dependencies]

[profile.release]
opt-level = 2
strip = true
