---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xindong.
--- DateTime: 2021/9/18 21:04
---

-- log_file挪到C++了，这里只是做个兼容
if not _G.log_file then
    _G.log_file = log
end

require 'main'

-->> sce_app_editor-patch >>
-- 编辑器补丁插槽（由 sce_app_editor-patch 应用注入，请勿手改）
local __ep_ok, __ep_err = pcall(require, 'sce_app_editor-patch.main')
if not __ep_ok and log_file and log_file.info then
    log_file.info('[sce_app_editor-patch] 框架入口加载失败: ' .. tostring(__ep_err))
end
--<< sce_app_editor-patch <<
