//! 补丁模块管理。
//!
//! 内置补丁模块以 `patches/<id>/` 目录形式存放在源码仓库，编译期 `include_str!` 嵌入 exe，
//! 保证单文件分发。启用模块 = 把模块文件加密写入编辑器 common 包下的框架目录：
//!
//! ```text
//! <common>/sce_app_editor-patch/
//!   main.lua            # 框架入口（AUTO-GENERATED，按启用列表重建）
//!   <模块id>/main.lua   # 模块文件
//! ```
//!
//! 启用状态即文件系统状态（扫描框架目录下的模块目录），无需额外状态文件。
//! 内核补丁注入的 `require 'sce_app_editor-patch.main'` 会加载该入口。

use super::crypto;
use std::fs;
use std::path::{Path, PathBuf};

/// 注入到 common 包下的框架目录名（与本仓库同名）
pub const PATCH_DIR_NAME: &str = "sce_app_editor-patch";

/// 一个内置补丁模块
pub struct PatchModule {
    /// 模块 id（目录名，同时是 require 路径的一段）
    pub id: &'static str,
    /// 显示名（中文）
    pub name: &'static str,
    /// 功能描述
    pub description: &'static str,
    /// 模块文件：(模块目录内相对路径, 文件内容)
    pub files: &'static [(&'static str, &'static str)],
}

/// 全部内置补丁模块（新增模块在此注册 + patches/ 下放文件）
pub fn builtin_modules() -> Vec<PatchModule> {
    vec![PatchModule {
        id: "hello",
        name: "示例补丁",
        description: "验证补丁链路：加载时输出日志，暴露全局标记 __EDITOR_PATCH__，并报告关键函数的解禁状态。",
        files: &[("main.lua", include_str!("../../patches/hello/main.lua"))],
    }]
}

/// 框架目录：<common>/sce_app_editor-patch
pub fn patch_dir(common_dir: &Path) -> PathBuf {
    common_dir.join(PATCH_DIR_NAME)
}

/// 当前已启用的模块 id 列表（扫描框架目录下含 main.lua 的子目录）
pub fn enabled_modules(common_dir: &Path) -> Vec<String> {
    let mut ids = Vec::new();
    let dir = patch_dir(common_dir);
    if let Ok(entries) = fs::read_dir(&dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() && path.join("main.lua").is_file() {
                if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                    ids.push(name.to_string());
                }
            }
        }
    }
    ids.sort();
    ids
}

/// 启用/关闭一个模块，并重建框架入口
pub fn set_module(common_dir: &Path, module: &PatchModule, enable: bool) -> Result<(), String> {
    let dir = patch_dir(common_dir).join(module.id);
    if enable {
        for (rel, content) in module.files {
            let path = dir.join(rel);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).map_err(|e| format!("创建目录失败: {e}"))?;
            }
            crypto::write_lua(&path, content)?;
        }
    } else if dir.exists() {
        fs::remove_dir_all(&dir).map_err(|e| format!("删除 {} 失败: {e}", dir.display()))?;
    }
    regenerate_entry(common_dir)
}

/// 按当前启用列表重建框架入口 main.lua（AUTO-GENERATED，加密写入）
pub fn regenerate_entry(common_dir: &Path) -> Result<(), String> {
    let dir = patch_dir(common_dir);
    fs::create_dir_all(&dir).map_err(|e| format!("创建 {} 失败: {e}", dir.display()))?;

    let ids = enabled_modules(common_dir);
    let mut text = String::from(
        "-- AUTO-GENERATED by sce_app_editor-patch（编辑器补丁），请勿手改\n\
         -- 本文件按已启用的补丁模块列表重建\n\
         local modules = {",
    );
    for id in &ids {
        text.push_str(&format!(" '{id}',"));
    }
    text.push_str(" }\n");
    text.push_str(
        "for _, id in ipairs(modules) do\n\
         \x20   local ok, err = pcall(require, 'sce_app_editor-patch.' .. id .. '.main')\n\
         \x20   if not ok then\n\
         \x20       log_file.info('[sce_app_editor-patch] 模块[' .. id .. ']加载失败: ' .. tostring(err))\n\
         \x20   end\n\
         end\n",
    );

    crypto::write_lua(&dir.join("main.lua"), &text)
}
